-- insert
insert into community_post 
(POST_NUMBER,COMMUNITY_CONTENT,COMMUNITY_TITLE,FILE_ATTACHIMENT,COMMUNITY_DATE,VIEW_COUNT,MEMBER_ID,COMMUNITY_NUMBER) 
values('POST51','강의추천1','한국샘 강의를 추천합니다','1','2023-10-25',412,'ceromi123','C03'),
('POST52','강의추천3','지리샘 강의를 추천합니다','1','2023-11-07',412,'ceromi123','C03');

-- select
select COMMUNITY_POST.COMMUNITY_TITLE, COMMUNITY.COMMUNITY_NAME,  COMMUNITY_POST.FILE_ATTACHIMENT, COMMUNITY_POST.COMMUNITY_CONTENT
from COMMUNITY_POST 
INNER JOIN COMMUNITY ON COMMUNITY_POST.COMMUNITY_NUMBER = COMMUNITY.COMMUNITY_NUMBER;

-- update
update community_post 
set COMMUNITY_CONTENT = '추천드린 강좌 내용을 수정합니다.',FILE_ATTACHIMENT='1' 
where POST_NUMBER = 'POST51' 
;

-- delete
delete from community_post where POST_NUMBER = 'POST51';