--  게시판 CRUD
-- CREATE
INSERT INTO COMMUNITY_POST_CONNECTION (COMMUNITY_NUMBER)
VALUES ('HUN')
;
-- READ 
SELECT * FROM COMMUNITY_POST_CONNECTION;
-- UPDATE
UPDATE COMMUNITY_POST_CONNECTION 
SET COMMUNITY_NUMBER = 'LEE' 
WHERE COMMUNITY_NUMBER = 'HUN'
;
-- DELETE
DELETE FROM COMMUNITY_POST_CONNECTION
WHERE COMMUNITY_NUMBER='LEE'
;