	-- MEMBER CRUD
-- CREATE
INSERT INTO member (MEMBER_ID, PW, MEMBER_NAME, POSITION, BIRTH, EMAIL, SMS_AD, EMAIL_AD, MEMBER_LECTURE, MEMBER_SIGNUP_LECTURE_LIST, TEST_RESULT)
VALUES ('MEMBER_ID', 'PW', 'MEMBER_NAME', 'POSITION', 'BIRTH', 'EMAIL', 'SMS_AD', 'EMAIL_AD', 'MEMBER_LECTURE', 'MEMBER_SIGNUP_LECTURE_LIST', '2')
;
-- READ
SELECT * from member
;
-- UPDATE
UPDATE member 
SET MEMBER_ID = 'MEMBER_ID_CHANGE' 
WHERE PW = 'PW'
;
-- DELETE
DELETE FROM member
WHERE MEMBER_ID='MEMBER_ID_CHANGE'
;