	-- mypage_selftest CRUD    
-- CREATE
INSERT INTO mypage_selftest (TEST_QUESTION_UID, TEST_QUESTION, TEST_ANSWER_UID, TEST_ANSWER, MEMBER_ID)
VALUES ('TEST_QUESTION_UID', 'TEST_QUESTION', 'TEST_ANSWER_UID', 'TEST_ANSWER', 'MEMBER_ID')
;
-- READ
SELECT * from mypage_selftest
;
-- UPDATE
UPDATE mypage_selftest 
SET TEST_QUESTION_UID = 'TEST_QUESTION_UID_CHANGE' 
WHERE TEST_QUESTION = 'TEST_QUESTION'
;
-- DELETE
DELETE FROM mypage_selftest
WHERE MEMBER_ID='TEST_QUESTION_UID_CHANGE'
;