
CREATE TABLE MEMBER
(
  MEMBER_ID                  VARCHAR(100) NOT NULL COMMENT '아이디',
  PW                         VARCHAR(100) NULL     COMMENT '비밀번호',
  MEMBER_NAME                VARCHAR(100) NULL     COMMENT '이름',
  POSITION                   VARCHAR(100) NULL     COMMENT '권한',
  BIRTH                      VARCHAR(100) NULL     COMMENT '생년월일',
  EMAIL                      VARCHAR(100) NULL     COMMENT '이메일주소',
  SMS_AD                     VARCHAR(100) NULL     COMMENT 'SMS광고수신',
  EMAIL_AD                   VARCHAR(100) NULL     COMMENT '이메일광고수신',
  MEMBER_LECTURE             VARCHAR(100) NULL     COMMENT '나의강의',
  MEMBER_SIGNUP_LECTURE_LIST VARCHAR(100) NULL     COMMENT '수강신청내역',
  TEST_RESULT                INTEGER      NULL     COMMENT '테스트결과',
	PRIMARY KEY (MEMBER_ID)
) COMMENT '사용자';

CREATE TABLE STATISTICS
(
  STATISTICS_DATE      VARCHAR(100) NOT NULL COMMENT '날짜',
  MEMBER_COUNT         INTEGER      NULL     COMMENT '회원수',
  SIGNUP_LECTURE_COUNT INTEGER      NULL     COMMENT '수강신청수',
  POST_COUNT           INTEGER      NULL     COMMENT '글작성수'
) COMMENT '통계관리';


CREATE TABLE COMMUNITY_LECTURE
(
  COMMUNITY_NUMBER   VARCHAR(100) NULL     COMMENT '게시판번호',
  POST_NUMBER        VARCHAR(100) NULL     COMMENT '게시글번호',
  ID                 VARCHAR(100) NULL     COMMENT '아이디',
  TITLE              VARCHAR(100) NULL     COMMENT '제목',
  POSTING_DATE       VARCHAR(100) NULL     COMMENT '작성일',
  VIEW_COUNT         INTEGER      NULL     COMMENT '조회수',
  PAGE_NUMBER        INTEGER      NULL     COMMENT '페이지번호'
) COMMENT '강좌게시판';

CREATE TABLE COMMUNITY_LECTURER
(
  COMMUNITY_NUMBER   VARCHAR(100) NULL     COMMENT '게시판번호',
  POST_NUMBER        VARCHAR(100) NULL     COMMENT '게시글번호',
  TITLE              VARCHAR(100) NULL     COMMENT '제목',
  ID                 VARCHAR(100) NULL     COMMENT '아이디',
  POSTING_DATE       VARCHAR(100) NULL     COMMENT '작성일',
  VIEW_COUNT         INTEGER      NULL     COMMENT '조회수',
  PAGE_NUMBER        INTEGER      NULL     COMMENT '페이지번호'
) COMMENT '강사게시판';

CREATE TABLE COMMUNITY_NOTICE
(
  COMMUNITY_NUMBER   VARCHAR(100) NULL     COMMENT '게시판번호',
  POST_NUMBER        VARCHAR(100) NULL     COMMENT '게시글번호',
  TITLE              VARCHAR(100) NULL     COMMENT '제목',
  ID                 VARCHAR(100) NULL     COMMENT '아이디',
  POSTING_DATE       VARCHAR(100) NULL     COMMENT '작성일',
  VIEW_COUNT         INTEGER      NULL     COMMENT '조회수',
  PAGE_NUMBER        INTEGER      NULL     COMMENT '페이지번호'
) COMMENT '공지사항';

CREATE TABLE COMMUNITY_POST
(
  COMMUNITY_NUMBER   VARCHAR(100) NULL     COMMENT '게시판번호',
  COMMUNITY_CONTENT  VARCHAR(100) NULL     COMMENT '게시글내용',
  COMMUNITY_COMMENT  VARCHAR(100) NULL     COMMENT '게시글댓글',
  COMMUNITY_TITLE    VARCHAR(100) NULL     COMMENT '게시글제목',
  FILE_ATTACHIMENT   VARCHAR(100) NULL     COMMENT '첨부파일'
) COMMENT '게시글';

CREATE TABLE COMMUNITY_STUDENT
(
  COMMUNITY_NUMBER   VARCHAR(100) NULL     COMMENT '게시판번호',
  POST_NUMBER        VARCHAR(100) NULL     COMMENT '게시글번호',
  TITLE              VARCHAR(100) NULL     COMMENT '제목',
  ID                 VARCHAR(100) NULL     COMMENT '아이디',
  POSTING_DATE       VARCHAR(100) NULL     COMMENT '작성일',
  VIEW_COUNT         INTEGER      NULL     COMMENT '조회수',
  PAGE_NUMBER        INTEGER      NULL     COMMENT '페이지번호'
) COMMENT '학생게시판';

CREATE TABLE LECTURE_REVIEW
(
  SEARCH_WORD       VARCHAR(100) NULL     COMMENT '검색어(수업후기게시판)',
  POST_NUMBER       VARCHAR(100) NULL     COMMENT '글번호(수업후기게시판)',
  POST_TITLE        VARCHAR(100) NULL     COMMENT '제목(수업후기게시판)',
  POST_REVIEW_COUNT INTEGER      NULL     COMMENT '게시글리뷰수(수업후기게시판)',
  POSTING_USER      VARCHAR(100) NULL     COMMENT '작성자(수업후기게시판)',
  POSTING_DATE      VARCHAR(100) NULL     COMMENT '작성일(수업후기게시판)',
  VIEW_COUNT        INTEGER      NULL     COMMENT '조회수(수업후기게시판)',
  PAGE_NUMBER       INTEGER      NULL     COMMENT '페이지번호(수업후기게시판)'
) COMMENT '수업 후기 게시판';

CREATE TABLE LECTURE_SIGNUP_LIST
(
  PAGE_NUMBER    INTEGER      NULL     COMMENT '페이지번호',
  LECTURE_NAME   VARCHAR(100) NULL     COMMENT '강좌이름',
  LECTURE_DETAIL VARCHAR(100) NULL     COMMENT '강좌상세'
) COMMENT '강좌신청목록';

CREATE TABLE LECTURE_SIGNUP
(
  POLL_QUESTION VARCHAR(100) NULL     COMMENT '설문질문',
  POLL_ANSWER   VARCHAR(100) NULL     COMMENT '설문답변',
  MEMBER_UID    VARCHAR(100) NULL     COMMENT '회원UID'
) COMMENT '강좌신청';

CREATE TABLE MEMBER_LOG
(
  ID           VARCHAR(100) NOT NULL COMMENT '아이디',
  LOGIN_DATE   VARCHAR(100) NULL     COMMENT '로그인시간',
  LOGIN_STATUS VARCHAR(100) NULL     COMMENT '로그인상태'
) COMMENT '로그인';

CREATE TABLE MYPAGE_LECTURE
(
  FORUM_UID          VARCHAR(100) NOT NULL COMMENT '게시판UID',
  SEARCH_WORD        VARCHAR(100) NULL     COMMENT '검색어',
  POST_NUMBER        VARCHAR(100) NULL     COMMENT '글번호',
  POST_TITLE         VARCHAR(100) NULL     COMMENT '제목',
  POST_COMMENT_COUNT INTEGER      NULL     COMMENT '게시글댓글수',
  POSTING_MEMBER     VARCHAR(100) NULL     COMMENT '작성자',
  POSTING_DATE       VARCHAR(100) NULL     COMMENT '작성일',
  VIEW_COUNT         INTEGER      NULL     COMMENT '조회수',
  PAGE_NUMBER        INTEGER      NULL     COMMENT '페이지번호'
) COMMENT '내 강좌보기';

CREATE TABLE MYPAGE_SELFTEST
(
  MEMBER_UID        VARCHAR(100) NOT NULL COMMENT '회원UID',
  TEST_QUESTION_UID VARCHAR(100) NULL     COMMENT '시험문항UID',
  TEST_QUESTION     VARCHAR(100) NULL     COMMENT '시험문항',
  TEST_ANSWER_UID   VARCHAR(100) NULL     COMMENT '시험답변UID',
  TEST_ANSWER       VARCHAR(100) NULL     COMMENT '시험답변'
) COMMENT '자기실력테스트';

CREATE TABLE MYPAGE_SELFTEST_RESULT
(
  MEMBER_UID          VARCHAR(100) NOT NULL COMMENT '회원UID',
  WRONG_QUESTION_UID  VARCHAR(100) NULL     COMMENT '틀린문제번호',
  WRONG_QUESTION_TYPE VARCHAR(100) NULL     COMMENT '틀린문제유형',
  MEMBER_NAME         VARCHAR(100) NULL     COMMENT '회원이름',
  MEMBER_TEST_SCORE   VARCHAR(100) NULL     COMMENT '회원시험점수'
) COMMENT '자기실력테스트결과';

CREATE TABLE MYPAGE_SIGNUP_LECTURELIST
(
  MEMBER_UID                 VARCHAR(100) NOT NULL COMMENT '회원UID',
  ENROLMENT_LECTURE_TITLE    VARCHAR(100) NULL     COMMENT '수강신청강의이름',
  ENROLMENT_LECTURE_LECTURER VARCHAR(100) NULL     COMMENT '수강신청강사이름'
) COMMENT '수강강좌확인';


CREATE TABLE POST_COMMENT
(
  COMMENT_NUMBER  VARCHAR(100) NOT NULL COMMENT '댓글번호',
  POST_NUMBER     VARCHAR(100) NULL     COMMENT '게시판번호',
  COMMENT_CONTENT VARCHAR(100) NULL     COMMENT '댓글내용',
  ID              VARCHAR(100) NULL     COMMENT '작성자아이디',
  POST_DATE            VARCHAR(100) NULL     COMMENT '작성일'
) COMMENT '댓글';
