
CREATE TABLE MYPAGE_SIGNUP_LECTURELIST
(
  MEMBER_UID                 VARCHAR(100) NOT NULL COMMENT '회원UID',
  ENROLMENT_LECTURE_TITLE    VARCHAR(100) NULL     COMMENT '수강신청강의이름',
  ENROLMENT_LECTURE_LECTURER VARCHAR(100) NULL     COMMENT '수강신청강사이름'
) COMMENT '수강강좌확인';
