
CREATE TABLE MYPAGE_SELFTEST
(
  MEMBER_UID        VARCHAR(100) NOT NULL COMMENT '회원UID',
  TEST_QUESTION_UID VARCHAR(100) NULL     COMMENT '시험문항UID',
  TEST_QUESTION     VARCHAR(100) NULL     COMMENT '시험문항',
  TEST_ANSWER_UID   VARCHAR(100) NULL     COMMENT '시험답변UID',
  TEST_ANSWER       VARCHAR(100) NULL     COMMENT '시험답변'
) COMMENT '자기실력테스트';
