
CREATE TABLE MYPAGE_LECTURE
(
  FORUM_UID          VARCHAR(100) NOT NULL COMMENT '게시판UID',
  SEARCH_WORD        VARCHAR(100) NULL     COMMENT '검색어',
  POST_NUMBER        VARCHAR(100) NULL     COMMENT '글번호',
  POST_TITLE         VARCHAR(100) NULL     COMMENT '제목',
  POST_COMMENT_COUNT INTEGER      NULL     COMMENT '게시글댓글수',
  POSTING_MEMBER     VARCHAR(100) NULL     COMMENT '작성자',
  POSTING_DATE       VARCHAR(100) NULL     COMMENT '작성일',
  VIEW_COUNT         INTEGER      NULL     COMMENT '조회수',
  PAGE_NUMBER        INTEGER      NULL     COMMENT '페이지번호'
) COMMENT '내 강좌보기';
