insert into mypage_lecture (FORUM_UID, SEARCH_WORD, POST_NUMBER, POST_TITLE, POST_COMMENT_COUNT, POSTING_MEMBER, POSTING_DATE, VIEW_COUNT, PAGE_NUMBER) 
values ('BB01', null, 11, 'abc', 23, 'mike', '2022-02-14', 15, 1);
insert into mypage_lecture (FORUM_UID, SEARCH_WORD, POST_NUMBER, POST_TITLE, POST_COMMENT_COUNT, POSTING_MEMBER, POSTING_DATE, VIEW_COUNT, PAGE_NUMBER) 
values ('BB01', null, 12, 'abcfds', 22, 'nina', '2022-02-12', 15, 1);