
CREATE TABLE MYPAGE_SELFTEST_RESULT
(
  MEMBER_UID          VARCHAR(100) NOT NULL COMMENT '회원UID',
  WRONG_QUESTION_UID  VARCHAR(100) NULL     COMMENT '틀린문제번호',
  WRONG_QUESTION_TYPE VARCHAR(100) NULL     COMMENT '틀린문제유형',
  MEMBER_NAME         VARCHAR(100) NULL     COMMENT '회원이름',
  MEMBER_TEST_SCORE   VARCHAR(100) NULL     COMMENT '회원시험점수'
) COMMENT '자기실력테스트결과';
