
CREATE TABLE POST_COMMENT
(
  COMMENT_NUMBER  VARCHAR(100) NOT NULL COMMENT '댓글번호',
  POST_NUMBER     VARCHAR(100) NULL     COMMENT '게시판번호',
  COMMENT_CONTENT VARCHAR(100) NULL     COMMENT '댓글내용',
  ID              VARCHAR(100) NULL     COMMENT '작성자아이디',
  POST_DATE       VARCHAR(100) NULL     COMMENT '작성일'
) COMMENT '댓글';
