
CREATE TABLE community_post
(
  COMMUNITY_NUMBER   VARCHAR(100) NULL     COMMENT '게시판번호',
  COMMUNITY_CONTENT  VARCHAR(100) NULL     COMMENT '게시글내용',
  COMMUNITY_COMMENT  VARCHAR(100) NULL     COMMENT '댓글'
) COMMENT '게시글';
