
CREATE TABLE community_post
(
  COMMUNITY_NUMBER   VARCHAR(100) NULL     COMMENT '게시판번호',
  COMMUNITY_CONTENT  VARCHAR(100) NULL     COMMENT '게시글내용',
  COMMUNITY_COMMENT  VARCHAR(100) NULL     COMMENT '게시글댓글',
  COMMUNITY_TITLE    VARCHAR(100) NULL     COMMENT '게시글제목',
  FILE_ATTACHIMENT   VARCHAR(100) NULL     COMMENT '첨부파일'
) COMMENT '게시글';
