
CREATE TABLE MEMBER_LOG
(
  ID           VARCHAR(100) NOT NULL COMMENT '아이디',
  LOGIN_DATE   VARCHAR(100) NULL     COMMENT '로그인시간',
  LOGIN_STATUS VARCHAR(100) NULL     COMMENT '로그인상태'
) COMMENT '로그인';
